export enum CARS {
  GET_CARS_FAILURE = 'GET_CARS_FAILURE',
  GET_CARS_FULFILL = 'GET_CARS_FULFILL',
  GET_CARS_REQUEST = 'GET_CARS_REQUEST',
  GET_CARS_SUCCESS = 'GET_CARS_SUCCESS',
  GET_CARS_TRIGGER = 'GET_CARS_TRIGGER',
}

export enum SLICE_KEYS {
  CARS = 'cars',
}

export enum SLICE_NAMES {
  CARS = 'CARS',
}
